MYSQL_CONCPP_DIR = "C:\\Program Files\\MySQL\\MySQL Server 8.0"
CPPFLAGS = -I $(MYSQL_CONCPP_DIR)/include -L $(MYSQL_CONCPP_DIR)/lib64
LDLIBS = -lmysqlcppconn8
CXXFLAGS = -std=c++11
mysql_devapi : mysql_devapi.cpp